### ISSUE TITLE
How often will this be updated?

### ISSUE THREAD

**Issue by vanta240i** [reallymello/zipcode-detail-lookup#1]
Hello,

I haven't found any discussion page or anything similar of the sort on github, but I did want to make sure and confirm this with maintainer... 

How often will zips be updated with results from USPS or something like that? 

Can there be two seperate packages: One for client-side with cached results, One server-side to be able to dynamically load new addresses on startup from source?

Thank you for your time!

**Comment by reallymello** [comment]
The idea would be as the underlying list is republished I'd release a new patch version so if you update the package you'd get the latest zips with it. I'm relying on a 3rd party source that collates it from various sources. They last published April 2024, but I am not sure what their future cadence is. I hope that clarifies things! Best regards.
